### ISSUE TITLE
Replace componentWillReceiveProps in CopyButton

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mr-ui#108]
Similar to https://github.com/mapbox/mr-ui/issues/91

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
>  
>  * Move data fetching code or side effects to componentDidUpdate.
>  * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
>  * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
>  
>  Please update the following components: CopyButton

**Comment by tristen** [comment]
Same with control-file! https://github.com/mapbox/mr-ui/blob/fb9f4911c805265b7d6df54fd60e4023169e3f95/src/components/control-file/control-file.js#L89
