### ISSUE TITLE
React 16: Popover Positioner does not attach to document root

### ISSUE THREAD

**Issue by elifitch** [mapbox/mr-ui#110]
With React 15, as one would expect, Popover Positioner attaches to the document. With React 16 (I tested React 16.4 and React 16.13), Popover positioner attaches to the element that spawned the popover.

React 15 (expected):
![image](https://user-images.githubusercontent.com/2495933/87590673-2af06800-c6b5-11ea-9730-3c5969b1908d.png)

React 16 (uh oh):
![image](https://user-images.githubusercontent.com/2495933/87590998-a6eab000-c6b5-11ea-8776-80990b3d7817.png)

**Comment by chrisbrainerd** [comment]
Is there any visual or functional problems we've noticed? Afaik this is expect. `react-displace` operates [one way](https://github.com/davidtheclark/react-displace/blob/master/src/displace.js#L67) on react<=15 (`ReactDOM.unstable_renderSubtreeIntoContainer` which mounts the whole component elsewhere in the react tree) vs on react 16+ where it uses the new Portal API, which mounts the component as a child in the component tree like in the second screenshot, but then maintains instructions to render the actual DOM node for that component somewhere specific in the DOM.

**Comment by mathewantony31** [comment]
Haven't seen any bugs related to this
