### ISSUE TITLE
`themItemContainer ` prop is not used in the tablist

### ISSUE THREAD

**Issue by shabnomnom** [mapbox/mr-ui#116]
Per documentation https://mapbox.github.io/mr-ui/#tablist `themItemContainer ` is a valid prop for the tablist, but I was not able to utilize this prop. Looking closer looks like `themItemContainer ` is never rendered beyond the initial definition. `themItemContainer ` https://github.com/mapbox/mr-ui/blob/d2e0a19caa9790325953ba3487b94cfae2153b19/src/components/tab-list/tab-list.js#L40

**Comment by tristen** [comment]
Closing as we'll be removing this as part of #180
