### ISSUE TITLE
Use passive listeners to improve performance

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mr-ui#118]
We should consider using passive listeners to improve performance (ref https://web.dev/uses-passive-event-listeners/). I've noticed this Lighthouse recommendation on pages that use `PopoverTrigger`, but there may be other components to update.

Example:

```diff
-this.triggerElement.addEventListener('touchstart', this.blockHover);
+this.triggerElement.addEventListener('touchstart', this.blockHover, {passive: true});
```

**Comment by tristen** [comment]
Going to close as the internal handling of popover will be replaced by Radix
