### ISSUE TITLE
Drop ControlDate

### ISSUE THREAD

**Issue by tristen** [mapbox/mr-ui#125]
[It's currently not in use](https://github.com/search?q=user%3Amapbox+user%3Amapbox-collab+filename%3Apackage.json+%27%40mapbox%2Fmr-ui%2Fcontrol-date%27&type=code), requires custom CSS, dependencies, and Native date selection is better these days.

**Comment by katydecorah** [comment]
👍 Docs team is in favor of dropping

**Comment by mbullington** [comment]
This is actually used here: https://github.com/mapbox/to-fix/blob/master/src/components/shared/components/filter/DateFilter.jsx

cc @chapko

**Comment by mbullington** [comment]
Also used here: https://github.com/mapbox/admin/blob/master/src/components/add-atlas-license-modal.js

Gonna leave this ticket alone for now, I used the filter `user:mapbox user:mapbox-collab ControlDate` and made sure users were using `mr-ui`.
