### ISSUE TITLE
LoaderLocal css is broken due to assembly 1.0.0 changes

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mr-ui#131]
Right now loader sticks in top left corner.

<img width="381" alt="Screen Shot 2021-06-21 at 10 17 59 AM" src="https://user-images.githubusercontent.com/108094/122786484-fa785d00-d279-11eb-852e-c0fbbb003a96.png">

The markup needs to be more like:

```html
<div className="absolute top left right bottom flex flex--center-cross flex--center-main">
  <div className="loading" />
</div>
```

**Comment by tristen** [comment]
Done in #165
