### ISSUE TITLE
Add Spacing component

### ISSUE THREAD

**Issue by mbullington** [mapbox/mr-ui#135]
In working on Studio, I noticed there's a pattern where in a list, we want elements `1..n` to have spacing in-between them and end up doing something with `Array.prototype.map` in most cases to accomplish this. With keys, it gets a little hairy.

I took a shot at creating a higher-level component for this called `Spacing`, and was curious what others thought and if it would be useful outside of Studio inside `mr-ui`.

https://gist.github.com/mbullington/7024a44c8a20ad1ee318788c9a96c074

**Comment by chrisbrainerd** [comment]
Personally this feels like overkill, this is a problem CSS can solve _real_ easily though idk how we feel about stuff like this with assembly. Say we have a list of items and we want a margin of 5px between them all:
```js
// my-component.jsx
<ul>
  {items.map((item, i) => <li key={i} className='my-item>{item}</li>
</ul>
...
// my-component.css
.my-item:not(:first-child) {
  margin-top: 5px;
}
```
I genuinely don't know how to do this in assembly, I know tailwind has some pseudo-selectors built in like `first` and `last` (for `:first-child` and `:last-child` respectively). Talking through it now I'm honestly leaning more towards keeping things as is - the extra level of div nesting doesn't feel great and the solution we have does work fine (and allow the flexibility to solve problems like striping every other row, different handling for first, second, and last, etc).

**Comment by mbullington** [comment]
I agree that maybe a better solution is finding a way in Assembly to do stuff like this, and that the div nesting doesn't *feel* good.

However I'd argue that this doesn't really change how things work right now, at least in parts of Studio. The way I've seen to do it (from existing code) is:

```javascript
{groups.map(([key, component], i) => (
  <div key={key} className={i !== 0 ? 'mt24' : ''}>
    {component}
  </div>
))}
```

**Comment by mbullington** [comment]
Decided not to go this path as it seems like slightly overkill, and could lead to inconsistencies within Studio about when to use vs. when not to use.

**Comment by mbullington** [comment]
I was learning Tailwind CSS over the weekend and came onto this: https://tailwindcss.com/docs/gap

Apparently in most modern browsers (Safari is only 14.1 and mobile 14.5, the bleeding versions of Big Sur and iOS 14), `gap` CSS property also works for flexbox.

I think this a really elegant way to handle Spacing without being overbearing, and once Safari support evens out, I think this would be cool to add to Assembly.
