### ISSUE TITLE
Simplify the styling of ControlFile

### ISSUE THREAD

**Issue by tristen** [mapbox/mr-ui#137]
The default styling of the control button is doing too much

`btn align-l bg-gray-faint py6 px12 round-full w-full txt-s link--gray txt-normal`

<img width="138" alt="Screen Shot 2021-08-26 at 10 21 57 AM" src="https://user-images.githubusercontent.com/61150/130980175-e53c033d-e222-4d70-8f72-694e03e24f2d.png">

This breaks styling conventions in Studio and should not be as opinionated as it is. This should just use `btn`

<img width="150" alt="Screen Shot 2021-08-26 at 10 22 44 AM" src="https://user-images.githubusercontent.com/61150/130980316-4f1833e9-26df-42fd-a777-6da56ef6f44a.png">

**Comment by samanpwbb** [comment]
Our controlfile should visually mirror https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file so it is recognizable as a file input. So, button on left, state label to the right by default. Styled to match the rest of the mapbox design system.
