### ISSUE TITLE
Consider allowing programmatic access to colors

### ISSUE THREAD

**Issue by mbullington** [mapbox/mr-ui#145]
# Description

For certain instances (like working with GL JS layers) it would be useful to have programmatic access to the MBX Assembly color palette. https://mapbox.github.io/mr-ui/

Although I know this goes against the Assembly-first approach, so would love feedback on if this ticket would head `mr-ui` in the wrong direction or expose too "loose" of an API.

Primer, GitHub's design system, does this: https://github.com/primer/primitives

cc @tristen @chrisbrainerd

**Comment by tristen** [comment]
Does this work for your needs?

```js
import assemblyCssVariables from '@mapbox/mbx-assembly/dist/variables.json';
console.log(assemblyCssVariables['gray'])
```

**Comment by mbullington** [comment]
Closing as the solution works, and making this easier probably makes more sense in Assembly. Thanks all for the discussion!
