### ISSUE TITLE
React 16 warnings in `react-displace`

### ISSUE THREAD

**Issue by mbullington** [mapbox/mr-ui#150]
# Description

https://github.com/davidtheclark/react-displace is used as a wrapper around React Portals in `mr-ui`, Studio, etc.

It's also used by `react-aria-modal`, which we also use, and was also created by David (https://github.com/davidtheclark/react-aria-modal#readme). Although it looks like @tristen has write access to this!

Should we update https://github.com/davidtheclark/react-displace to remove these errors? I could also see a vendored version that was rewritten with React hooks and only Portals support (`react-displace` checks for portals), but unsure how that would interact with `react-aria-modal`.

This afaik is the only place left in `mr-ui` where we use UNSAFE methods (or their unprefixed equivalents).

**Comment by kscoulter** [comment]
Solution: get rid of the dependency

**Comment by tristen** [comment]
Dependency was removed in https://github.com/mapbox/mr-ui/tree/mr-ui%403.0.0!
