### ISSUE TITLE
Rewrite control-select using radix select

### ISSUE THREAD

**Issue by badiuoanaalexandra** [mapbox/mr-ui#178]
- Rewrite control-select component using [radix react-select](https://www.radix-ui.com/docs/primitives/components/select)
- Typescript should be used
- Keep as much as possible of the current functionality

Below you can find information about current usage of control-select. 

**control-select**
**Used in**: mapbox/install-atlas, mapbox/admin, mapbox/studio, mapbox/help, mapbox/account, mapbox/search-lab, mapbox/www.mapbox.com, mapbox/dr-ui

**Props used**: id, value, label, themeLabel, onChange, options, themeControlSelect, disabled, themeControlWrapper, themeControlSelectContainer, data-test, getControlProps(‘country’), aside, validationError

There are repos that might be used on mobile phone, so we should also check how the select works on mobile. 

Taken from mr-ui audit document https://docs.google.com/document/d/1x-fCsbmvcsYV2Y49cC2eFiV_XonECpOnkYAkGBtcNIM/

**Comment by tristen** [comment]
> There are repos that might be used on mobile phone, so we should also check how the select works on mobile.

Confirming it works on mobile but I kind of wish it would default to native behavior:

![IMG_CEE0AB72A190-1](https://user-images.githubusercontent.com/61150/185217960-90020387-100c-4edb-bfd8-d26bc68fd98b.jpeg)

**Comment by tristen** [comment]
I think I'm going to cautiously _not_ use https://www.radix-ui.com/docs/primitives/components/select for this. Mobile usability is not great and the native behavior is pretty darn good.
