### ISSUE TITLE
Remove components that are not needed

### ISSUE THREAD

**Issue by badiuoanaalexandra** [mapbox/mr-ui#179]
According to the mr-ui audit document and how we want our library to be used, there are a few components that can be removed:

- **badge** - same behavior can be achieved with tooltip and perhaps a cssClass for the trigger if we want them all to look the same
- **control-card** - not used anywhere
- **control-legend** - not used anywhere, doesn’t seem to do anything special. I think having control-label is enough
- **go-link** - I don’t think a link should be a component, but just have default css for links 
- **heading** - same as link I think we should have default styles for the headings and not a component for them
- **new-tab-link** - normal link should be used for this, with default styling that just opens a new tab. No need for a component

The list should be discussed with @tristen and @VLuisa

**Comment by tristen** [comment]
Going to quickly take care of this one and send over to @VLuisa for review.

**Comment by tristen** [comment]
Closed per https://github.com/mapbox/mr-ui/pull/183
