### ISSUE TITLE
Plan to migrate components to Radix

### ISSUE THREAD

**Issue by aswamina** [mapbox/mr-ui#182]
Based on the ticket for auditing mr-ui components ....

You can see the findings in the document below that has general access for all people in the organisation.
https://docs.google.com/document/d/1x-fCsbmvcsYV2Y49cC2eFiV_XonECpOnkYAkGBtcNIM

This document should help check what components are being used, in which repos and what props are being used when rewriting a component.

### Acceptance Criteria
- Prioritized list and a plan to migrate to Radix
- Plan to migrate Studio components to use these components and be available to customers

**Comment by tristen** [comment]
@aswamina just flagging that there's an epic that _I think_ is the intention of this one? See https://github.com/mapbox/mr-ui/issues/156
