### ISSUE TITLE
Allow the `children` prop to be optional

### ISSUE THREAD

**Issue by tristen** [mapbox/mr-ui#201]
I have a use case where I want to broadcast from the toast component after the onExit callback of another component and it would be nice if I didn't have to pass children like so:

```jsx
import React, { useState } from 'react';
import Toast from '@mapbox/mr-ui/toast';
import CustomComponent from './custom-component';

function myProp() {
  const [done, setDone] = useState(true);
  return (
    <>
      <CustomComponent onExit={() => setDone(true)}
      <Toast active={done} />
    </>
  );
}
```

Considering this is a controlled component, I wonder if we should just omit a children prop altogether. Thoughts @VLuisa?

**Comment by VLuisa** [comment]
@tristen that makes a lot of sense!
