### ISSUE TITLE
Calls to getWindow() prevent successful use in SSR

### ISSUE THREAD

**Issue by chriswhong** [mapbox/mr-ui#210]
I recently attempted to update to the latest `mr-ui` in one of the Mapbox docs sites, and kept getting a `window not available` error during build.

After some digging, I traced it to the `Icon` component, which calls the util `getWindow()`.  `getWindow()` throws an error if `window` does not exist, making it impossible to render `Icon` in an SSR build.

https://github.com/mapbox/mr-ui/blob/main/src/components/icon/icon.tsx#L32

cc/ @tristen, I am curious what you would recommend for using mr-ui in an SSR environment.  `Icon` is used heavily across many of our docs sites.

**Comment by tristen** [comment]
@chriswhong is `getComputedStyle` method available in this SSR build? 

I'd like to refactor this getWindow utility out of mr-ui tbh. I think it does more harm than good. We can conditionally check for `window?.getComputedStyle` in that component and mock the window object for jest [here](https://github.com/mapbox/mr-ui/blob/main/src/setupTests.ts)

**Comment by chriswhong** [comment]
> is getComputedStyle method available in this SSR build?

`window` is undefined so `getComputedStyle` wouldn't be available AFAIK.
