### ISSUE TITLE
MbxAvatar component?

### ISSUE THREAD

**Issue by katydecorah** [mapbox/mr-ui#22]
I'm often creating a circular avatar that usually looks like this:

```
<div
className='w60 h60 round-full inline-block'
style={{
  backgroundImage: 'url(' + user.photo + ')',
  backgroundSize: '100%',
  backgroundRepeat: 'no-repeat'
}}
/>
```

Result: 
![image](https://user-images.githubusercontent.com/2180540/43596284-e10c9f5a-964c-11e8-93a9-3ffb0c69538d.png)

Anyone see a need for this type of component? Of the top of my head, I can imagine the ability to pass different sizes through. Perhaps border options, too.

**Comment by davidtheclark** [comment]
@katydecorah I don't know of anywhere else that uses this right now. (If anybody else does, please chime in.) But it could prove useful, yeah. 

If you'd like to work on this component, let's give it a shot 👍 It would be nice to make it a generic "Image inside a circle" component. And I wonder if we can make it flexible enough that you don't have to apply the image using a CSS background image property, but could also use an `<img>` tag?

**Comment by katydecorah** [comment]
Oooh great suggestions! I'll give it a shot

**Comment by katydecorah** [comment]
No longer needed
