### ISSUE TITLE
Strategy for Form and its controls

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mr-ui#24]
To match our current patterns, we should have two standard sizes for all form elements: small (as in the dense style editor) and large (as everywhere else).

My impression is that `Form`s current validation system is working fine, so we should carry the same patterns into `Mbx*` components. Studio's style editor remains the only place where we want to use a different validation pattern.

However, I'd be fine with changing the default styling of validation to match @angel's suggestion a little while ago: turn the input's borders red, when possible, and just provide red text for the error message (without a red background & outline).

**Comment by tristen** [comment]
Closing as stale
