### ISSUE TITLE
Improve Prism integration with CodeSnippet

### ISSUE THREAD

**Issue by elifitch** [mapbox/mr-ui#30]
`<CodeSnippet>` is set up to use [highlight.js](https://highlightjs.org/) for pretty syntax highlighting. HL.js is a pretty big library, even if you only import what you need, it can still be dozens of KB for a single language. In fact, in Studio, we're just using the parser for HTML, and it still added 100kb to our bundle.

I think we could get it looking just as good by using [prism.js](https://prismjs.com/) instead, which is a much smaller alternative.

**Comment by davidtheclark** [comment]
CodeSnippet does not currently import and use a syntax highlighter at all, it just expects you to highlight the code in your own way and provide a theme that fits it. So I believe you could right now switch your highlighter library to Prism and use the theme prop to pass in Prism-targeting CSS.

If you do this and settle on a great syntax-highlighting theme, maybe we could end up building that highlighting functionality directly into CodeSnippet, with CodeSnippet importing Prism. Or we could provide helper functions to make it easy to use Prism.

**Comment by elifitch** [comment]
I didn't notice that we allow highlighting CSS to be passed as a prop, that's a handy feature!

I think it'd be worth switching the default highlighting scheme to be prism classes though instead of hljs.

Should I reformat this issue or close and open a new one?

**Comment by davidtheclark** [comment]
@elifitch I retitled the issue. What Prism theme do you like? I'm curious, because I recently struggled picking a Prism theme.

**Comment by tristen** [comment]
Punting as mr-ui doesn't import highlight.js directly and there's not totally clear evidence to use prism (i.e more popular over hl.js)
