### ISSUE TITLE
ControlFile icon takes up its own line 

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mr-ui#45]
![2018-09-07 at 11 55 am](https://user-images.githubusercontent.com/628431/45237977-0810f380-b295-11e8-95ad-4fd50f5b8c7e.png)

It should look like this older example:

<img width="317" alt="screen shot 2018-09-07 at 11 57 22 am" src="https://user-images.githubusercontent.com/628431/45238030-3abaec00-b295-11e8-84cd-8ab22442f91e.png">

We'll also want to check the layout of the trash icon to delete a file you've already selected.

@otherwiseman is this something you'd be interested in fixing? I'll be out on vacation next week but would be happy to review a PR fixing it when I'm back, or @kepta or @danswick could.

**Comment by samanpwbb** [comment]
@mzdraper fixed this: https://github.com/mapbox/mr-ui/commit/d6180497f626b65d0dec4672083980bb8493d1f5
