### ISSUE TITLE
Can't input or close top Modal

### ISSUE THREAD

**Issue by lshig** [mapbox/mr-ui#46]
Recent changes to Modal, possibly `[fix] Update react-aria-modal to get some bug fixes and focus-management improvements.`, breaks Modal in the Account Dashboard. It works fine when there's only 1 Modal being rendered, however we have a user experience where there is a Modal being rendered on top of another Modal. It'd be ideal if we could get this specific scenario to work again in mr-ui since I imagine it'll be a long time from now till we have bandwidth to change the design and user experience.

Example below with creating a token and 2FA:
<img width="685" alt="screen shot 2018-10-17 at 10 17 30 am" src="https://user-images.githubusercontent.com/9087698/47104326-00c6f900-d1f6-11e8-8cdd-3166b61dded2.png">

I'm unable to click into the inputs, type any characters, or close the modal by clicking the `x`. Only way out is by clicking off the top Modal and in the overlay.

**Comment by davidtheclark** [comment]
Sounds to me like the place to look for the cause of this is in the way the modals are trapping focus.

**Comment by davidtheclark** [comment]
@lshig Just released v4 of react-aria-modal, which might fix this nested-modals problem: https://github.com/davidtheclark/react-aria-modal/blob/master/CHANGELOG.md#400

**Comment by tristen** [comment]
Closing as stale
