### ISSUE TITLE
Implement Underreact's new hot-reload feature

### ISSUE THREAD

**Issue by danswick** [mapbox/mr-ui#58]
ref: https://github.com/mapbox/mr-ui/pull/55#issuecomment-439905714

Once the port to Underreact is complete, we should take advantage of [Underreact's hot-releading feature](https://github.com/mapbox/underreact#how-do-i-enable-hot-module-reloading-).

**Comment by tristen** [comment]
Stale by the move to CRA in https://github.com/mapbox/mr-ui/tree/mr-ui%403.0.0
