### ISSUE TITLE
In PageHeader, doc click event listener should be attached and removed in lifecycle hooks, not render methods

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mr-ui#65]
We'll want to attach and remove the event listeners in `componentDidMount`, and we'll also want to remove them in `comonentWillUnmount`. I believe these are the expected and bug-frees place to attach and detach non-React event listeners.

cc @danswick

**Comment by danswick** [comment]
The listener was attached and removed in those lifecycle events (https://github.com/mapbox/mr-ui/pull/60/commits/47019f3d4b4a11a364e89c5a6aaa3ee315a4646d#diff-fae640c3677d082e033cc3beb0c626ceL72), but I moved them per this comment https://github.com/mapbox/mr-ui/pull/60#issuecomment-448027204. Maybe I put them in the wrong place, but my read on that comment was that the listeners should not be attached or removed inside `componentDidMount` and `componentWillUnmount` anymore. If there's a way to address that comment without moving out of those two lifecycle events, I could use some help implementing.

**Comment by davidtheclark** [comment]
Sorry, I meant `componentDidUpdate` ... 🤦‍♂️ 

In `componentDidUpdate` we'd say "Was the menu previously closed but is now open? If so, attach an event listener. Was the menu previously open but is now closed? If so, detach the event listener." And in `componentWillUnmount` we'll always detach the event listener — this change we should make regardless. This way we'd avoid triggering side effects from the render method.

That said, the other alternative to consider is keeping the event listeners where they were (attach only on mount, detach on unmount) but only having one test case.
