### ISSUE TITLE
Chevronous text inline prop

### ISSUE THREAD

**Issue by elifitch** [mapbox/mr-ui#70]
the `inline-block` class applied to the outer element here https://github.com/mapbox/mr-ui/blob/master/src/components/chevronous-text/chevronous-text.js#L44 makes migrating from mapbox react components difficult. If we could add an `inline` prop (defaulting to true to avoid shipping a breaking change) to toggle this class on and off, that'd be awesome.

**Comment by davidtheclark** [comment]
@lshig why did you add the `inline-block` class in the first place?

**Comment by lshig** [comment]
`inline-block` may be a unnecessary leftover artifact from when I thought the chevron arrow was meant to be a fixed size no matter what the text size was. We can probably remove it.
