### ISSUE TITLE
Badge component

### ISSUE THREAD

**Issue by lshig** [mapbox/mr-ui#72]
The Account Dashboard has a very simple `Badge` component to label features as `Beta` or `Coming soon`. I propose we move this component here and be design opinionated on padding, coloring, and font size. It will take in a `text` prop and margins will be left up to a wrapper or sibling elements around it.

<img width="247" alt="screen shot 2019-02-14 at 11 43 43 am" src="https://user-images.githubusercontent.com/9087698/52813170-0de1e080-304e-11e9-9e9a-66a775f39717.png">
<img width="261" alt="screen shot 2019-02-14 at 11 44 06 am" src="https://user-images.githubusercontent.com/9087698/52813173-0faba400-304e-11e9-8bfb-d24c777c5c76.png">
<img width="272" alt="screen shot 2019-02-14 at 11 45 06 am" src="https://user-images.githubusercontent.com/9087698/52813178-12a69480-304e-11e9-899f-e1d1133952bb.png">

Would love feedback on use cases and color themes! cc: @angel @mapbox/docs @mapbox/studio

**Comment by HeyStenson** [comment]
Exciting @lshig! I definitely agree that this would be a good addition to mr-ui. 

From a docs perspective, some potential use cases I can think of right now are:
- APIs that are in public beta
- API features that are public beta
- SDK features that are in public beta 
- SDK features that are only available to certain customer types (for ex. only Enterprise customers can use Offline routing for the [iOS](https://docs.mapbox.com/ios/navigation/overview/offline-routing/) and [Android](https://docs.mapbox.com/android/navigation/overview/offline-routing/) Navigation SDKs)
- Tutorials that cover products that are only available if they've been purchased (ex. [Enterprise boundaries-related tutorials](https://docs.mapbox.com/help/tutorials/data-joins-with-enterprise-boundaries/))

**Comment by tristen** [comment]
If it's just a stylistic treatment, could this be a [style util](https://github.com/mapbox/mr-ui/blob/facb76c502989eef9c312bd944afca9833c35f4d/src/components/utils/styles.js#L3-L22) instead?

**Comment by lshig** [comment]
Oops I should've updated this. We're also adding an optional `Tooltip` wrapper around this `Badge` component. This will be used in the Account Dashboard and our documentation sites.

<img width="197" alt="screen shot 2019-02-28 at 12 26 28 pm" src="https://user-images.githubusercontent.com/9087698/53596274-3ab8ec00-3b54-11e9-93fc-63e6d029489c.png">
