### ISSUE TITLE
shallowEqualObjects error in Icon component

### ISSUE THREAD

**Issue by elifitch** [mapbox/mr-ui#73]
It looks like when you pass a nested object to `<Icon>` as a prop, `shallowEqualObjects` throws an error if it is passed an object with wonky keys and the `allowedObjectKeys` flag is not set. This caused some issues when Studio was migrating to Mr UI, as there were a handful of instances where we were passing a nested object to MRC's Icon component, and we didn't catch all of them when migrating.

`<Icon>` worked great for us once we removed these instances, but maybe we should add a prop to components that use shallowEqualObject to allow users to configure it? Maybe documenting this change to aid folks in migrating to Mr-UI?

**Comment by tristen** [comment]
A show-stopping error is unfortunate. Could this not throw and instead `console.warn` that a key is not recognized?

**Comment by kepta** [comment]
> shallowEqualObjects throws an error if it is passed an object with wonky keys and the allowedObjectKeys flag is not set.

@elifitch could you give an example of this object with wonky keys. 

> <Icon> worked great for us once we removed these instances, but maybe we should add a prop to components that use shallowEqualObject to allow users to configure it? 

I understand it might be a bit painful to handle all those objects and the errors, but revealing an internal implementation (shallowEqualObject) and allowing users to configure it, might not be a good idea.

> A show-stopping error is unfortunate. Could this not throw and instead console.warn that a key is not recognized?

I guess the error is there to reap the benefits of shallow comparing and minimising the deep comparison. Do you think just a warn would be sufficient @tristen ?

**Comment by tristen** [comment]
> Do you think a warn would be sufficient @tristen ?

It's an optimization detail relevant to developers so I think a warn is sufficient? At least, that seems like a common pattern with other libraries and saves the end user from coming across it.

**Comment by tristen** [comment]
Closing as stale
