### ISSUE TITLE
hasPointer prop for popover positioner doesn't work

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/mr-ui#76]
hasPointer isn't actually used for anything: https://github.com/mapbox/mr-ui/blob/master/src/components/popover/popover-positioner.js#L37

**Comment by davidtheclark** [comment]
I _think_ it should be passed to `calculatePosition` but is not: https://github.com/mapbox/mr-ui/blob/cd02fc413b772f06fdb541c510148eb196de7b85/src/components/popover/popover-positioner.js#L100-L114
