### ISSUE TITLE
Popover within a modal disables input focus

### ISSUE THREAD

**Issue by dereklieu** [mapbox/mr-ui#82]
In Studio, when a user chooses to customize a monochrome color style, we render the color picker in a popover that is the child of a modal. When this happens, the inputs (that are not buttons or `type="submit"` in the popover are not focusable.

#### Popover within a modal

![modal-popover](https://user-images.githubusercontent.com/1590802/59458511-75772500-8dcf-11e9-9acc-6d50a35259de.gif)

#### Popover not within a modal

![non-modal-popover](https://user-images.githubusercontent.com/1590802/59458521-7ad46f80-8dcf-11e9-8132-d45138839733.gif)

Ref https://github.com/mapbox/studio/issues/11636

Looking into this a bit, I'm guessing that `focus-trap` is what's preventing this construction from working as expected. Would love some input (pun intended) on whether this is likely the case, and if there are any strategies for disabling or white-listing a particular focus-trapped instance.

**Comment by davidtheclark** [comment]
Yes, this is definitely the case, @dereklieu. I think this is a similar issue to https://github.com/mapbox/mr-ui/issues/46

**Comment by dereklieu** [comment]
Tried a few different approaches. Here's what I got.

### Bumping the modal version

I bumped `react-aria-modal` up to v4 in this repo to [pull in better handling for nested focus traps](https://github.com/davidtheclark/react-aria-modal/blob/master/CHANGELOG.md#400). This did not resolve my issue. 

Had I been nesting one modal within another, this probably would have worked. However, the Popover component uses it's own copy of the `focus-trap` library so the local variable-based instance management introduced in newer versions of the `focus-trap` library doesn't apply.

(Rendering the popover with `trapFocus: true` alongside the modal crashed my browser in a very cool, spectacular way.)

Potential way forward: bump up `focus-trap` and `react-aria-modal` versions in this repo and make `focus-trap` a peer dependency in `react-aria-modal` which probably isn't a great idea.

### Specifying a render-to option

I hacked up a way to dynamically pass a `render-to` option to the `PopoverPositioner` component bundled with the [Popover](https://github.com/mapbox/mr-ui/blob/master/src/components/popover/popover-positioner.js#L187).

Then I added an empty `<div />` to the end of the current new style modal. It works but alignment is off.

![modal-popover-relative](https://user-images.githubusercontent.com/1590802/59474674-a4f05680-8dfc-11e9-801e-90853eb97055.gif)

Rendering the popover in a random place in the DOM and expecting positioning to be right seems far-fetched.

### Passing through the ability to pause focus-trap

For this one I bypassed `mr-ui/modal` altogether in favor of rendering `react-aria-modal` with `focusTrapPaused: true`. This works well.

![modal-popover-paused](https://user-images.githubusercontent.com/1590802/59474771-ed0f7900-8dfc-11e9-94fa-75ae3073b5cb.gif)

@davidtheclark I think the best way forward would be to pass this prop, perhaps with a prop name that makes it clear that it breaks accessibility. What do you think?

**Comment by davidtheclark** [comment]
Allow `mr-ui/modal` to pass a `focusTrapPaused` value through to `react-aria-modal` sounds good.

Another option to consider that we touched on yesterday: Create a new SimplePopover (or something like that) that does not use `react-displace`, so it *is* nested in whatever DOM subtree you put it in, and positions itself with simple absolute position instead of the Popover's complex algorithm. This should allow the SimplePopover to work within focus traps, I think. The downside of SimplePopover would be that it does not have adaptive positioning, so it should be used in contexts with predictable layout constraints.
