### ISSUE TITLE
Click events inside of tooltips inside of modals getting eaten

### ISSUE THREAD

**Issue by chrisbrainerd** [mapbox/mr-ui#85]
Minimal example: https://codesandbox.io/s/exciting-bassi-8zye4?fontsize=14

Originally thought it was only anchor tags but I tried it with a button's onClick and that doesn't work either, both get eaten.

**Comment by dereklieu** [comment]
This is pretty old so maybe no longer relevant to you @chrisbrainerd, but popping in to say that we had this problem in Studio, and added a `focusTrapPaused` prop to the [modal](https://mapbox.github.io/mr-ui/#modal) component - when set to true, the inputs in that example will work.

**Comment by tristen** [comment]
Haven't confirmed but I'm going to close as stale. The internal ingredients have been swapped out.
