### ISSUE TITLE
Change label proptypes to support elements

### ISSUE THREAD

**Issue by chrisbrainerd** [mapbox/mr-ui#87]
One common use case I've found is having a label that includes an icon or some semantic markup, like either of these:
```jsx
<ControlText
  id='name'
  label={<span>Who are you? <em>(this will be displayed publicly)</em></span>}
  onChange={this.handleFormChange}
  value={this.state.name}
/>
```

```jsx
<ControlText
  id='github'
  label={<span><FaGithubIcon />Github username</span>}
  onChange={this.handleFormChange}
  value={this.state.github}
/>
```

Under the hood, all the various `Control` elements use `ControlLabel`, which sets the label text here: https://github.com/mapbox/mr-ui/blob/master/src/components/control-label/control-label.js#L29

This code is still perfectly valid with the prop examples above, but because of the PropType that's set, it throws a warning in the console.

I'd propose we change it from `text: PropTypes.string.isRequired` to 
```js
text: React.PropTypes.oneOfType([
  React.PropTypes.string,
  React.PropTypes.element
]).isRequired
```

Optionally then it might make sense to rename `text` to something that more accurately describes the valid possibilities, though I'm unsure what specifically. Maybe just `label`?

**Comment by tristen** [comment]
Closing this for now. I waffled on convenience but I think forcing a uniform style to labels is important. There's also a workaround by _not_ providing the label to the control input and rolling with your own.
