### ISSUE TITLE
ControlSelect component's select value does not update on change

### ISSUE THREAD

**Issue by adrianababakanian** [mapbox/mr-ui#88]
When selecting an `option` from the dropdown, the `select` tag's `value` does not update. 

Issue can be demonstrated with the example at: https://mapbox.github.io/mr-ui/#controlselect

Originally noticed this at the Static Images API Playground style selection (https://github.com/mapbox/playground/issues/15).

**Comment by tristen** [comment]
Closing as mr-ui components will intentionally require control (i.e a new `value` must be provided by the consumer). I'm going to make the example https://mapbox.github.io/mr-ui/#controlselect more user friendly with a working implementation.
