### ISSUE TITLE
MbxUnderlineTabs component

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/mr-ui#9]
The details of this component are surprisingly difficult to get completely right, so I was thinking it could be a good first candidate for the `Mbx*` line of more opinionated components.

I'm of aware of 3 current variants that were deliberately styled:

<img width="338" alt="screen shot 2018-07-27 at 10 26 18 am" src="https://user-images.githubusercontent.com/628431/43337161-d97d40a6-9187-11e8-94fb-90fc7d7ca247.png">
<img width="214" alt="screen shot 2018-07-27 at 10 26 21 am" src="https://user-images.githubusercontent.com/628431/43337162-d991c6fc-9187-11e8-8281-5f2b3542bff8.png">
<img width="474" alt="screen shot 2018-07-27 at 10 26 25 am" src="https://user-images.githubusercontent.com/628431/43337163-d9a8575a-9187-11e8-9c1d-0de5a558c945.png">

Some variations in those patterns:

- Text size: `txt-xs`, `txt-s`, and regular.
- Whether inactive items are dimmed or not.
- Whether active items are bold or not.
- Color of the active-item underline.
- Distance between items (corresponds to text size).
- Height (corresponds to text size).
- Underline length — whether it exceeds the text by a couple of pixels or not.
- Horizontal overflow: the page-shell subnav tabs scroll horizontally when they run out of space; the larger docs tabs grow a "More" button with a dropdown.
- Hover state: only the small version in Studio has a hover state, darkening the dimmed text.

I'm leaning towards make the following choices (knowing that the Studio team is going to be best suited to maintaining their own variant):

- Don't dim the inactive tabs, so there's no danger of it looking disabled.
- Two sizes: small (current subnav) and large.
- Bold active items.
- Trim underline length to the text, so the component can be flush with the edge of its container.
- Active underline matches text color.
- Inactive items get blue text on hover (?).
- Build in the ability to transform some or all of the items into a dropdown.

@maikyon @angel I know you both worked on design for the two variants outside of Studio. Any opinions on the above?

**Comment by dasulit** [comment]
Another variation: Underline width. Looks like across account and the mapbox.com website, the underline is 2px and set on the inside of the container, while in Studio the underline is 1px and flush with the bottom keyline.

**Comment by davidtheclark** [comment]
@dasulit Ah, I think that flush with the bottom keyline is probably what everybody *wants*, but that turns out to be one of tricky points (like using bold for the active item without causing width to bounce when you change). So I'll plan to make the underline overlap the bottom keyline unless there are hearty objections.

**Comment by angel** [comment]
@davidtheclark I actually like when the active underline is taller and is above the gray line, but I'm fine with it overlapping with the gray line as long as the blue is still sticking out. I think it's clearer and more useful when it's not fully flushed with the line and when it's 3px in height for the larger version as least.

**Comment by angel** [comment]
@davidtheclark also there's this one in accounts with no gray line:
![image](https://user-images.githubusercontent.com/103496/43426027-48e18e4c-9409-11e8-9885-fe426d9c6feb.png)
